Cool_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import STATIC_URL, STATIC_ROOT
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
# Login url
    path('login/', views.user_login, name='Login'),
    # Logout url
    path('logout/', views.user_logout, name='Logout'),
    #Register URL
    path('register/', views.register, name='Register'),
    path('about/', views.about, name='about'),
    path('', views.home, name='home'),
    # Operation result page, use to show error after operation fail
    path('request_result/?error=<str:error>', views.request_result, name='request_result_error'),
    # Operation result page, use to show status after operation success
    path('request_result/?status=<str:status>', views.request_result, name='request_result_ok'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'
urlpatterns = [
    path('new_search/', views.new_search, name='new_search'),
    path('all_mobiles/?page=<int:page>', views.all_mobiles, name='all_mobiles'),
    path('mobiles_byPrices/?dev=<str:dev>&low=<int:low>&high=<int:high>&page=<int:page>',
         views.search_PriceRange, name='mobile_byprice'),
    path('submit_photo/', views.submit_photo, name='submit_photo'),
    path('view_photos/?mode=<int:mode>&page=<int:page>', views.view_photos, name='view_photos'),
    path('view_photos/?mode=<int:mode>&page=<int:page>&username=<str:username>',
         views.view_photos, name='view_photos'),
    path('view_drafts/?mode=<int:mode>&page=<int:page>', views.view_drafts, name='view_drafts'),
    path('photo/<uuid:pk>', views.photo_detail, name='photo_detail'),
    path('drafts/publish', views.publish_draft, name='publish_draft'),
    path('drafts/delete', views.delete_draft, name='delete_draft'),
]

templates/base/NavBar.html
<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-info text-light">
        <a class="navbar-brand" href="/">TuAnh Listing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!-- Drop down for photos-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="photoDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Photos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="photoDropDown">
                        <a class="dropdown-item" href="{% url 'frontend:submit_photo' %}">Submit Photos</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'frontend:view_photos' 0 1 %}">View Photos</a>
                        {% if user.is_authenticated %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'frontend:view_drafts' 0 1 %}">View My Draft</a>
                        {% endif %}
                    </div>
                </li>
                <!-- Drop down for Mobiles -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="mobileDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Mobiles
                    </a>
                    <div class="dropdown-menu" aria-labelledby="mobileDropDown">
                        <a class="dropdown-item" href="{% url 'frontend:all_mobiles' 1%}">All Mobiles</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'frontend:mobile_byprice' 'Mobile' 0 4000000 1%}">Below 4.000.000</a>
                        <a class="dropdown-item" href="{% url 'frontend:mobile_byprice' 'Mobile' 4000000 10000000 1%}">4.000.000 - 10.000.000</a>
                        <a class="dropdown-item" href="{% url 'frontend:mobile_byprice' 'Mobile' 10000000 1000000000 1%}">Above 10.000.000</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'frontend:new_search' %}">Detail Search</a>
                    </div>
                </li>
                <!-- Login/Logout -->
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href={% url 'Logout' %}>Logout</a>
                    {% else %}
                        <a class="nav-link" href={% url 'Login' %}>Login</a>
                    {% endif %}
                </li>

                <!-- About page -->
                <li class="nav-item">
                    <a class="nav-link" href={% url 'about' %}>About</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <!-- Login status -->
                {% if user.is_authenticated %}
                    <span class="navbar-text">Welcome {{ user.username }}</span>
                {% else %}
                    <span class="navbar-text">Guest</span>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/base/footer.html
{% load static %}

<footer class="page-footer font-small pt-4 bg-info">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mt-md-0 mt-3">
        <h5 class="text-light">Footer Content</h5>
        <p class="text-light">This website is created by Tu Anh for illustration purposes</p>
      </div>
      <div class="col-md-4 mb-md-0 mb-3">
        <h5 class="text-light">Links</h5>
        <ul>
          <li><a class="text-light" href="{%  url 'home' %}">Main Page</a></li>
          <li><a class="text-light" href="/">Laptop</a></li>
          <li><a class="text-light" href="/">Others</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
            <p class="h6">&copy All right Reversed.<a class="text-light ml-2" href="/" target="_blank">TuAnh Listing</a></p>
        </div>
      </div>
  </div>

</footer>

templates/base/headData.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Web Scraper GUI</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
</head>

templates/base/intro.html
<div class="container" style="padding: 3em 0 1em 0">
    <h1 class="text-center">Tu Anh Electronics Scraper</h1>
    <div class="row" style="padding: 3em 0 1em 0">

        <div class="col">
            <span class="d-flex justify-content-center mb-4" style="font-size: 80px; color: #EE6E73;">
                <i class="fas fa-balance-scale"></i>
            </span>
            <p class="text-center">Multiple Sources</p>
            <p class="text-secondary text-center">Compare prices from different sources</p>
        </div>

        <div class="col">
            <span class="d-flex justify-content-center mb-4" style="font-size: 80px; color: skyblue;">
                <i class="fas fa-bolt"></i>
            </span>
            <p class="text-center">Latest data</p>
            <p class="text-secondary text-center">Always the newest, freshest data</p>
        </div>

        <div class="col">
            <span class="d-flex justify-content-center mb-4" style="font-size: 80px; color: dimgray;">
                <i class="fas fa-history"></i>
            </span>
            <p class="text-center">Search History</p>
            <p class="text-secondary text-center">Get your search histor</p>
        </div>
    </div>
</div>

templates/base/paginator.html
<div class="pagination right" style="padding: 1em 2em 0 0">
    {% if items.has_previous %}
        <li class="waves-effect"><a href="{% url 'frontend:all_mobiles' 1%}"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
        <li class="waves-effect"><a href="{% url 'frontend:all_mobiles' items.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
    {%  else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    {% endif %}

    {% for num in items.paginator.page_range %}
        {% if items.number == num %}
            <li class="active"><a href="{% url 'frontend:all_mobiles' num%}">{{ num }}</a></li>
        {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
            <li class="waves-effect"><a href="{% url 'frontend:all_mobiles' num%}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    {% if items.has_next %}
        <li class="waves-effect"><a href="{% url 'frontend:all_mobiles' items.next_page_number%}"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="{% url 'frontend:all_mobiles' items.paginator.num_pages %}"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    {% else %}
        <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
</div>

templates/base/paginator_byPrice.html
<nav aria-label="Page navigation main">
    <ul class="pagination">
        {% if items.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:all_mobiles' dev low high 1 %}">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:all_mobiles' dev low high items.previous_page_number %}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">First</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
        {% endif %}
        {% for i in items.paginator.page_range %}
            {% if items.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }}<span class="sr-only">(current)</span></a>
                </li>
          {% elif i > items.number|add:'-3' and i < items.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'frontend:all_mobiles' dev low high i %}">{{ i }}</a>
                </li>
          {% endif %}
        {% endfor %}
        {% if items.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:all_mobiles' dev low high items.next_page_number %}">&raquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:all_mobiles' dev low high items.paginator.num_pages %}">Last</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Last</a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/base/paginator_photos.html
<nav class="my-4" aria-label="Page navigation main">
    <ul class="pagination">
        {% if items.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:view_photos' mode 1 username %}">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:view_photos' mode items.previous_page_number username %}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">First</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
        {% endif %}
        {% for i in items.paginator.page_range %}
            {% if items.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }}<span class="sr-only">(current)</span></a>
                </li>
          {% elif i > items.number|add:'-3' and i < items.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'frontend:view_photos' mode num username %}">{{ i }}</a>
                </li>
          {% endif %}
        {% endfor %}
        {% if items.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:view_photos' mode items.next_page_number %}">&raquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'frontend:view_photos' mode items.paginator.num_pages mode num %}">Last</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Last</a>
            </li>
        {% endif %}
    </ul>
</nav>