Cool_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import STATIC_URL, STATIC_ROOT
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
# Login url
    path('login/', views.user_login, name='Login'),
    # Logout url
    path('logout/', views.user_logout, name='Logout'),
    #Register URL
    path('register/', views.register, name='Register'),
    path('about/', views.about, name='about'),
    path('', views.home, name='home'),
    # Operation result page, use to show error after operation fail
    path('request_result/?error=<str:error>', views.request_result, name='request_result_error'),
    # Operation result page, use to show status after operation success
    path('request_result/?status=<str:status>', views.request_result, name='request_result_ok'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'
urlpatterns = [
    path('new_search/', views.new_search, name='new_search'),
    path('all_mobiles/?page=<int:page>', views.all_mobiles, name='all_mobiles'),
    path('mobiles_byPrices/?dev=<str:dev>&low=<int:low>&high=<int:high>&page=<int:page>',
         views.search_PriceRange, name='mobile_byprice'),
    path('submit_photo/', views.submit_photo, name='submit_photo'),
    path('view_photos/?mode=<int:mode>&page=<int:page>', views.view_photos, name='view_photos'),
    path('view_photos/?mode=<int:mode>&page=<int:page>&username=<str:username>',
         views.view_photos, name='view_photos'),
    path('view_drafts/?mode=<int:mode>&page=<int:page>', views.view_drafts, name='view_drafts'),
    path('photo/<uuid:pk>', views.photo_detail, name='photo_detail'),
    path('drafts/publish', views.publish_draft, name='publish_draft'),
    path('drafts/delete', views.delete_draft, name='delete_draft'),
]

templates/photos/addPhoto.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
{%  include "base/headData.html" %}
<body>
{% include "base/NavBar.html" %}

<main>
    <div class="container">
        <h1 class="text-center">Submit New Photo</h1>
        {% if user.is_authenticated %}
        <div style="padding: 20px">
            {% crispy form form.helper %}
        </div>
        {% else %}
        <h5>Please <a href="{% url 'Login' %}">Log in</a> before submit your photos.</h5>
        {% endif %}
    </div>

</main>

{% include "base/footer.html" %}

templates/photos/photoItem.html
{% load filter %}
<div class="card my-3">

    <div class="card-img-top photo_div">
        <img src="{{ item.photo.url|get_thumbnail:size }}" height="100%" width="100%">
    </div>

    <div class="card-body" style="height: 150px">
        <h5 class="card-title">{{ item.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">*Submitted by {{ item.added_by.username }}</h6>
        <div class="card-text">
            Tags: {{ item.tags }}
        </div>
    </div>

    <div class="card-footer">
        <a class="btn btn-primary py-2" href="{% url 'frontend:photo_detail' item.uuid %}"><h5>View Details</h5></a>
    </div>

</div>

templates/photos/photo_detail.html
<!DOCTYPE html>
{% load static %}
{% load filter %}
<html lang="en">
{%  include "base/headData.html" %}

<body>
{% include "base/NavBar.html" %}
<main>
    <div class="container">
        {% if item.draft is True %}
            {% if user.is_authenticated is False or user.username != item.added_by.username %}
                <h5 class="text-left text-danger">
                    This photo is a draft. Please <a href="{% url 'Login' %}">log in</a> as submitter to view
                </h5>
            {% endif %}
        {% endif %}

        {% if item.draft is False or user.is_authenticated and user.username == item.added_by.username %}
            <h1 class="text-center text-dark">{{ item.title }}</h1>

            {% if error_message %}<p class="text-danger"><strong>{{ error_message }}</strong></p>{% endif %}
            <hr>
            <div class="row">

                <div class="col-6">
                    <h5 class="text-center text-info">Submited time: {{ item.created_at|convert_localtime }}</h5>
                </div>

                <div class="col-6">
                    <h5 class="text-center text-info">Submitted by: {{ item.added_by.username }}</h5>
                </div>
            </div>

            <hr>

            <div>
                <strong>Tag</strong>
                <code style="white-space: pre-line; overflow: scroll">
                    #{{ item.tags }}
                </code>
            </div>
            <hr>

            <div>
                <strong>Photo</strong>
            </div>
            <div style="height: 500px; padding: 2em 0 0 2em">
                <img src="{{ item.photo.url }}" height="100%" width="auto">
            </div>
        {% endif %}

        {% if item.draft is True and user.is_authenticated and user.username == item.added_by.username %}
            <div class="row mt-3">
                <div class="col-1">
                    <form action="{% url 'frontend:publish_draft' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value={{ item.uuid }}>
                        <button class="btn btn-primary" type="submit" name="publish">
                            Publish
                        </button>
                    </form>
                </div>
                <div class="col-1">
                    <form action="{% url 'frontend:delete_draft' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value={{ item.uuid }}>
                        <button class="btn btn-primary" type="submit" name="delete">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
</main>

{%  include 'base/footer.html' %}

</body>
</html>

templates/photos/viewDrafts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

{%  include "base/headData.html" %}

<body>
{% include "base/NavBar.html" %}

<main>
    {% include "base/intro.html" %}

     <!-- Buttons to select view mode -->
    <div class="container my-4">
        {% if mode == 0 %}
            <a class="btn btn-primary disabled" href="#"><i class="fas fa-arrow-up"></i> From Latest</a>
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 1 1 %}"><i class="fas fa-arrow-down"></i> From Oldest</a>
        {% elif mode == 1 %}
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 0 1 %}"><i class="fas fa-arrow-up"></i> From Latest</a>
            <a class="btn btn-primary disabled" href="#"><i class="fas fa-arrow-down"></i> From Oldest</a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 0 1 %}"><i class="fas fa-arrow-up"></i> From Latest</a>
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 1 1 %}"></i> From Oldest</a>
        {% endif %}
    </div>

    <div class="container">
        {% include "base/paginator_photos.html" with items=allData mode=mode%}
        <!-- Name of user -->
        <div class="container text-center">
             <h1>{{ user.username }}'s Drafts</h1>
        </div>

        <div class="row">
            {% for item in allData %}
                <div class="col col-md-4 col-lg-3 col-sm-auto">
                    {% include "photos/photoItem.html" with item=item size=size %}
                </div>
            {% endfor %}
        </div>
        {% include "base/paginator_photos.html" with items=allData mode=mode%}
    </div>
</main>

{% include "base/footer.html" %}
</body>
</html>

templates/photos/viewPhotos.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

{%  include "base/headData.html" %}

<body>
{% include "base/NavBar.html" %}

<main>
    {% include "base/intro.html" %}

     <!-- Buttons to select view mode -->
    <div class="container my-4">
        {% if mode == 0 %}
            <a class="btn btn-primary disabled" href="#"><i class="fas fa-arrow-up"></i> From Latest</a>
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 1 1 %}"><i class="fas fa-arrow-down"></i> From Oldest</a>
        {% elif mode == 1 %}
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 0 1 %}"><i class="fas fa-arrow-up"></i> From Latest</a>
            <a class="btn btn-primary disabled" href="#"><i class="fas fa-arrow-down"></i> From Oldest</a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 0 1 %}"><i class="fas fa-arrow-up"></i> From Latest</a>
            <a class="btn btn-primary" href="{% url 'frontend:view_photos' 1 1 %}"></i> From Oldest</a>
        {% endif %}
        <span class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i> By User
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for usr in all_users %}
                    <a class="dropdown-item" href="{% url 'frontend:view_photos' 2 1 usr.username %}">{{ usr.username }}</a>
                {% endfor %}
            </div>
        </span>
    </div>

    <div class="container">
        {% include "base/paginator_photos.html" with items=allData mode=mode%}
        <!-- Name of user -->
        {% if mode == 2 %}
            <div class="container text-center">
                 <h1>{{ username }}'s Photos</h1>
            </div>
        {% endif %}

        <div class="row">
            {% for item in allData %}
                <div class="col col-md-4 col-lg-3 col-sm-auto">
                    {% include "photos/photoItem.html" with item=item size=size %}
                </div>
            {% endfor %}
        </div>
        {% include "base/paginator_photos.html" with items=allData mode=mode%}
    </div>
</main>

{% include "base/footer.html" %}
</body>
</html>